#!/bin/sh
#
# Description: handles .exe extension of executables on Windows
#
# credit: aaronsvk @ https://github.com/Microsoft/WSL/issues/2003
command_not_found_handler() {
    if cmd.exe /c "(where $1 || (help $1 |findstr /V Try)) >nul 2>nul && ($* || exit 0)"; then
        return $?
    else
        if [ -x /usr/lib/command-not-found ]; then
            /usr/lib/command-not-found --no-failure-msg -- ${1+"$1"}
            return $?
        elif [ -x /usr/share/command-not-found/command-not-found ]; then
            /usr/share/command-not-found/command-not-found -- ${1+"$1"}
            return $?
        else
            printf "%s: command not found\n" "$1" >&2
            return 127
        fi
    fi
}
